# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8de49595264fbc33fb5d416c0b2e5906802f7b6224809017d01d53d889eaf8e5e89d82d89631444e7b6978c67f2041ca09e1df120dc19bf79f58b161b1d353c

test:
  secret_key_base: ac09d154ea92536bda560f6142698d72ae1d74a12fcc537bbded3039aa39cd2b3ee3c767a0042421bc964119beaf282827aa1dac478811ea7754aa35b5da6da5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
